name: CI Build

on:
  push:
    branches:
      - master

jobs:
  generator:
    name: auto generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: install build-dep
        run: |
          sudo apt install -y libgirepository1.0-dev libgudev-1.0-dev
      - name: build
        run: make
      - name: init git
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.email "justforlxz@gmail.com"
          git config --global user.name "justforlxz"
          cd ..
          git clone https://x-access-token:$API_TOKEN_GITHUB@github.com/linuxdeepin/go-gir.git
      - name: copy file
        run: |
          cd ..
          rm -rf go-gir/*
          cp -r go-gir-generator/out/src/github.com/linuxdeepin/go-gir/* go-gir/
      - name: add files
        run: |
          cd ..
          cd go-gir
          rm -rf ./**/.gitignore
          git add .
          date=$(date)
          git commit -m "auto generator at ${date}"
      - name: push
        run: |
          cd ..
          cd go-gir
          git push -f
